pipeline {
agent any

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Build Maven') {
        steps {
            sh 'mvn clean install -DskipTests'
        }
    }

    stage('Verify Docker') {
        steps {
            sh 'docker --version'
            sh 'docker ps'
        }
    }

    stage('Verify Build Artifacts') {
        steps {
            sh 'find . -name "*.jar"'
        }
    }
}

post {
    success {
        echo 'EventFlow CI/CD Pipeline Success!'
    }

    failure {
        echo 'Pipeline Failed!'
    }

    always {
        cleanWs()
    }
}


}
