pipeline {
agent any

```
stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Build Maven') {
        steps {
            sh 'mvn clean install -DskipTests'
        }
    }

    stage('Build Docker Images') {
        steps {
            sh 'docker compose build'
        }
    }

    stage('Deploy Containers') {
        steps {
            sh 'docker compose down'
            sh 'docker compose up -d'
        }
    }

    stage('Verify Deployment') {
        steps {
            sh 'docker ps'
        }
    }
}

post {

    success {
        echo 'EventFlow CI/CD Pipeline Success!'
    }

    failure {
        echo 'Pipeline Failed!'
    }

    always {
        cleanWs()
    }
}
```

}
