apiVersion: v1
kind: Secret
metadata:
  name: eventflow-secrets
  namespace: eventflow
type: Opaque
data:
  # Base64 encoded values
  JWT_SECRET: NDRDRTYzNTI2NjU1Nko1WDZOMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
  DB_PASSWORD: cm9vdA==
